# Antes de los servicios, defino anchors (como variables), para evitar confusiones.
# Docker ignora todo lo que comienza con x-
x-nextcloud-image: &nextcloud-image nextcloud:fpm-alpine

x-nextcloud-dir: &nextcloud-dir
  type: bind
  source: /srv/html-nextcloud
  target: /var/www/html

x-nfs-dir: &nfs-dir
  type: bind
  source: /srv/data-nextcloud/data
  target: /var/www/html/data

x-redis-image: &redis-image redis:8.4.0-alpine3.22

x-nginx-image: &nginx-image nginx:1.28.1-alpine3.23-slim

x-node_exporter-image: &node_exporter-image prom/node-exporter:v1.10.2

x-nextcloud_exporter-image: &nextcloud_exporter-image ghcr.io/xperimental/nextcloud-exporter

services:
  redis:
    image: *redis-image
    restart: always
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

  app:
    image: *nextcloud-image
    restart: always
    volumes:
      - <<: *nextcloud-dir
      - <<: *nfs-dir
    env_file:
      - .env.nextcloud
    depends_on:
      - redis

  web:
    image: *nginx-image
    restart: always
    ports:
      - 8080:80
    volumes: # Nginx solo debe realizar lecturas sobre los siguientes volúmenes.
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - <<: *nextcloud-dir
        read_only: true
      - <<: *nfs-dir
        read_only: true
    depends_on:
      - app

  cron:
    image: *nextcloud-image
    restart: always
    volumes:
      - <<: *nextcloud-dir
      - <<: *nfs-dir
    entrypoint: /cron.sh
    depends_on:
      - redis

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    volumes:
      - /srv/data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

#  node-exporter:
#    image: *node_exporter-image
#    container_name: node_exporter
#    ports:
#      - "9100:9100"
#    restart: always
#    volumes:
#      - '/proc:/host/proc:ro'
#      - '/sys:/host/sys:ro'
#      - '/:/rootfs:ro,rslave'
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.rootfs=/rootfs'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|home|host|etc)($$|/)'

#  nextcloud-exporter:
#    image: *nextcloud_exporter-image
#    container_name: nextcloud_exporter
#    ports:
#      - "9101:9205"
#    restart: always
#    env_file:
#      - .env.nextcloud_exporter
#    depends_on:
#      - app
